name: Daily Commit

on:
  schedule:
    # Runs every day at 07:30 UTC (you can change this to a specific hour/minute)
    - cron: '30 7 * * *'
  workflow_dispatch:  # allows manual trigger for testing

jobs:
  daily_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add daily commit (23f3000685@ds.study.iitm.ac.in)
        run: |
          date > last_run.txt
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add last_run.txt
          git commit -m "Daily commit: $(date)"
          git push
