name: Email

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  collect-iss-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: 23f3000685@ds.study.iitm.ac.in
        run: echo "Hello, world!"
